### PR TITLE
Adding support for Python 

### PR DESCRIPTION
**Pull request by rishabh-dhar**
Previously we only had support for shell sample code. This PR adds code snippets in python as well.

I have tested every python snippet that has been added, however additional checks would be good. 

Make sure you've checked off all these things before submitting:

- [x] This pull request isn't for a company's fork, it's intended for the upstream Slate shared by everybody.
- [x] This pull request is submitted to the `master` branch.
- [x] If it makes frontend changes, this pull request has been tested in the latest version of Firefox, Chrome, IE, and Safari.

### CODE REVIEW

**Comment by rishabh-dhar** [comment]
Hi @anas1md @jaywonder20 can I get a review on this please?

**Comment by rishabh-dhar** [comment]
Or if there is someone else who is better suited to review this, please let me know

**Review by jaywonder20 — COMMENTED** [review]
The Authentication part has no Sample request for python
Screenshot 2021-12-06 at 21 19 57

**Comment by anas1md** [comment]
> The Authentication part has no Sample request for python Screenshot 2021-12-06 at 21 19 57

@rishabh-dhar , yup everything else looks good!

**Comment by rishabh-dhar** [comment]
@anas1md @jaywonder20 can you please review and if it looks good merge and deploy

**Review by jaywonder20 — APPROVED** [review]
LGTM!

**Pull request merged**
